package edu.ucla.dt.studentservices.webservices.studentcontact.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-08-16T10:53:44.135-07:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://service.studentcontact.webservices.studentservices.dt.ucla.edu", name = "StudentContactWebService")
@XmlSeeAlso({ObjectFactory.class, edu.ucla.dt.studentservices.webservices.global.dataobject.ObjectFactory.class, edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StudentContactWebService {

    @WebResult(name = "StudentContactGetServiceResponse", targetNamespace = "http://dataobject.studentcontact.webservices.studentservices.dt.ucla.edu", partName = "getStudentContactInfoReturn")
    @WebMethod(action = "getStudentContactInfo")
    public edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.StudentContactGetServiceResponse getStudentContactInfo(
        @WebParam(partName = "arg_0_0", name = "StudentContactGetServiceRequest", targetNamespace = "http://dataobject.studentcontact.webservices.studentservices.dt.ucla.edu")
        edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.StudentContactGetServiceRequest arg00,
        @WebParam(partName = "request_headers", name = "webServiceRequestHeaders", targetNamespace = "http://dataobject.global.webservices.studentservices.dt.ucla.edu", header = true)
        edu.ucla.dt.studentservices.webservices.global.dataobject.WebServiceRequestHeaders requestHeaders
    );

    @WebResult(name = "StudentContactUpdateAddressesServiceResponse", targetNamespace = "http://dataobject.studentcontact.webservices.studentservices.dt.ucla.edu", partName = "updateAddressesReturn")
    @WebMethod(action = "updateAddresses")
    public edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.StudentContactUpdateAddressesServiceResponse updateAddresses(
        @WebParam(partName = "arg_0_1", name = "StudentContactUpdateAddressesServiceRequest", targetNamespace = "http://dataobject.studentcontact.webservices.studentservices.dt.ucla.edu")
        edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.StudentContactUpdateAddressesServiceRequest arg01,
        @WebParam(partName = "request_headers", name = "webServiceRequestHeaders", targetNamespace = "http://dataobject.global.webservices.studentservices.dt.ucla.edu", header = true)
        edu.ucla.dt.studentservices.webservices.global.dataobject.WebServiceRequestHeaders requestHeaders
    );

    @WebResult(name = "StudentContactUpdateServiceResponse", targetNamespace = "http://dataobject.studentcontact.webservices.studentservices.dt.ucla.edu", partName = "updateStudentContactInfoReturn")
    @WebMethod(action = "updateStudentContactInfo")
    public edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.StudentContactUpdateServiceResponse updateStudentContactInfo(
        @WebParam(partName = "request", name = "StudentContactUpdateServiceRequest", targetNamespace = "http://dataobject.studentcontact.webservices.studentservices.dt.ucla.edu")
        edu.ucla.dt.studentservices.webservices.studentcontact.dataobject.StudentContactUpdateServiceRequest request,
        @WebParam(partName = "request_headers", name = "webServiceRequestHeaders", targetNamespace = "http://dataobject.global.webservices.studentservices.dt.ucla.edu", header = true)
        edu.ucla.dt.studentservices.webservices.global.dataobject.WebServiceRequestHeaders requestHeaders
    );
}
